name: CI Pipeline

on:
  push:
    branches:[main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
    uses: actions/checkout@v5

    - name: Setup Node.js
    uses: actions/setup-node@v5
    with:
      node-version:20

    - name: Install dependencies
    run npm install

    - name: Run tests
    run npm run test

    - name: Run application
    run npm run run

    - name: Deploy to server
    run npm run deploy
    